// <auto-generated />
using System;
using Booker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booker.Api.Data.Migrations
{
    [DbContext(typeof(BookerContext))]
    [Migration("20260821132450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booker.Api.Models.Cruise", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CruiseVesselId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("CruiseVesselId");

                    b.ToTable("Cruises");

                    b.HasData(
                        new
                        {
                            id = new Guid("3d4e5f6a-7b8c-4d9e-8f0a-1b2c3d4e5f6a"),
                            CruiseVesselId = new Guid("0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c4d"),
                            DateFrom = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateTo = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Baltic Capitals"
                        },
                        new
                        {
                            id = new Guid("4e5f6a7b-8c9d-4e0f-9a1b-2c3d4e5f6a7b"),
                            CruiseVesselId = new Guid("1b2c3d4e-5f6a-4b7c-8d9e-0f1a2b3c4d5e"),
                            DateFrom = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateTo = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Norwegian Fjords"
                        },
                        new
                        {
                            id = new Guid("5f6a7b8c-9d0e-4f1a-8b2c-3d4e5f6a7b8c"),
                            CruiseVesselId = new Guid("2c3d4e5f-6a7b-4c8d-9e0f-1a2b3c4d5e6f"),
                            DateFrom = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateTo = new DateTime(2026, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mediterranean Odyssey"
                        });
                });

            modelBuilder.Entity("Booker.Api.Models.CruiseShip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VesselOperatorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VesselOperatorId");

                    b.ToTable("CruiseShips");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c4d"),
                            Capacity = 2200,
                            Description = "Flagship of the Aurora fleet.",
                            ImageUrl = "https://aurora-cruises.example.com/ships/northern-star.jpg",
                            ShipName = "MV Northern Star",
                            VesselOperatorId = new Guid("6f9a25a6-1c2f-4b7e-9d3a-0e8b1c4d5e6f")
                        },
                        new
                        {
                            Id = new Guid("1b2c3d4e-5f6a-4b7c-8d9e-0f1a2b3c4d5e"),
                            Capacity = 1800,
                            Description = "Ice-strengthened hull for arctic routes.",
                            ShipName = "MV Polar Dawn",
                            VesselOperatorId = new Guid("6f9a25a6-1c2f-4b7e-9d3a-0e8b1c4d5e6f")
                        },
                        new
                        {
                            Id = new Guid("2c3d4e5f-6a7b-4c8d-9e0f-1a2b3c4d5e6f"),
                            Capacity = 2600,
                            Description = "Largest ship in the Meridian fleet.",
                            ImageUrl = "https://meridian-voyages.example.com/ships/azure-horizon.jpg",
                            ShipName = "MV Azure Horizon",
                            VesselOperatorId = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e")
                        });
                });

            modelBuilder.Entity("Booker.Api.Models.VesselOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VesselOperators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f9a25a6-1c2f-4b7e-9d3a-0e8b1c4d5e6f"),
                            Description = "Scandinavian operator specializing in northern itineraries.",
                            IsActive = true,
                            Name = "Aurora Cruise Line",
                            Website = "https://aurora-cruises.example.com"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            Description = "Mediterranean and Atlantic leisure cruises.",
                            IsActive = true,
                            Name = "Meridian Voyages",
                            Website = "https://meridian-voyages.example.com"
                        });
                });

            modelBuilder.Entity("Booker.Api.Models.Cruise", b =>
                {
                    b.HasOne("Booker.Api.Models.CruiseShip", "CruiseVessel")
                        .WithMany()
                        .HasForeignKey("CruiseVesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CruiseVessel");
                });

            modelBuilder.Entity("Booker.Api.Models.CruiseShip", b =>
                {
                    b.HasOne("Booker.Api.Models.VesselOperator", "VesselOperator")
                        .WithMany("CruiseShips")
                        .HasForeignKey("VesselOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselOperator");
                });

            modelBuilder.Entity("Booker.Api.Models.VesselOperator", b =>
                {
                    b.Navigation("CruiseShips");
                });
#pragma warning restore 612, 618
        }
    }
}
